config/routes.rb
Blogmenow::Application.routes.draw do
  resources :posts do 
    resources :comments
  end
  
  root to: "pages#show", id: 'home'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts
  # has_many :photos

  scope :with_posts_count, -> { joins(:posts).select("categories.*, COUNT(posts.id) AS posts_count").group("categories.id") }

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include AASM

  belongs_to :post

  validates_presence_of :body

  aasm column: 'state' do 
    state :require_approval, initial: true
    state :approved
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  include Analytix::Model

  enum status: [:draft, :published]
  # enum status: { published: 1, draft: 0 }

  validates :title, presence: true
  has_many :comments

  has_many :taggings
  has_many :tags, through: :taggings

  belongs_to :category
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :posts, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_device_type

  include Transponder::Transmission

  def set_flash(type, object: nil)
    flash[:from] = action_name
    flash[:type] = type
    flash[:object_type] = object.class.name
    flash[:object_id]   = object.id
  end

private

  def set_device_type
    request.variant = :phone if browser.mobile?
  end

  def mobile_redirect
    redirect_to root_path + '#/' + mobile_redirect_path[action_name.to_sym].call
  end

  def ensure_mobile?
    request.variant == [:phone] and request.headers['Accept'] != '*/*'
  end

  def render_layout?
    request.variant == [:phone] ? false : true
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  respond_to :js, :html

  def create
    @post = Post.where(id: params[:post_id]).first
    @comment = @post.comments.build(comment_params)

    { 
      true  => -> { respond_with @post, @comment },
      false => -> { xms_error @comment } 
    }[@comment.save].call

    # if @comment.save
    #   respond_with @post, @comment
    # else
    #   xms_error @comment
    # end
  end

private 
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    render params[:id]
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  respond_to :html, :js
  before_filter :mobile_redirect, if: :ensure_mobile?

  def index
    @categories = Category.with_posts_count
    @tags_posts_count = Tagging.group("taggings.tag_id").count
    @posts = Post.published.includes(:tags).limit(100)
    respond_with @posts, layout: render_layout?
  end

  def show
    @post = get_post
    @post.track :views, [:uniques, request.remote_ip]
    respond_with @post, layout: render_layout?
  end

  def edit
    @post = get_post
  end

  def update
    @post = get_post
    if @post.update_attributes(post_params)
      set_flash :success, object: @post
      redirect_to posts_path
    else
      set_flash :error, object: @post
      render :edit
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      set_flash :success, object: @post
      redirect_to posts_path
    else
      set_flash :error, object: @post
      render :new
    end
  end

private
  
  def mobile_redirect_path
    { index: -> { posts_path } ,
      show:  -> { post_path(params[:id]) } }
  end

  def get_post
    Post.where(id: params[:id]).first
  end

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/flash_helper.rb
module FlashHelper
  def render_flash
    render 'flash' if can_flash?
  end

  def can_flash?
    flash.keys.sort == [:from, :object_id, :object_type, :type] and \
    flash.to_hash.values.compact.count == flash_values_count
  end

  def flash_values_count
    action_name == "create" ? 3 : flash.keys.count
  end

  def flash_object
    flash[:object_type].classify.constantize.where(id: flash[:object_id]).first
  end

  def flash_path
    File.join(controller_name, 'flash', flash[:from].to_s, flash[:type].to_s)
  end

  def flash_color_ifs
    if flash[:type] == :success
      'alert-success'
    elsif flash[:type] == :error
      'alert-danger'
    elsif flash[:type] == :warn
      'alert-warning'
    elsif flash[:type] == :info
      'alert-info'
    end
  end

  def flash_color_case
    case flash[:type]
    when :success then 'alert-success'
    when :error   then 'alert-danger'
    when :warn    then 'alert-warning'
    when :info    then 'alert-info'
    end
  end

  def flash_color
    { success: 'alert-success',
      error:   'alert-danger',
      notice:  'alert-info',
      warn:    'alert-warning' }[flash[:type]]
  end

end

app/helpers/phones_helper.rb
module PhonesHelper
  def panel_link path: nil, icon: nil, text: nil
    render 'application/phone/panel_link', path: path, icon_name: icon, text: text
  end
end

app/helpers/posts_helper.rb
module PostsHelper

end

app/views/application/_error_list.html.erb
<ul>
<% target.errors.each do |e| %>
  <li><%= e.to_s.titleize %>: <%= target.errors[e][0] %></li>
<% end %>
</ul>

app/views/application/_flash.html.erb
<div class='alert <%= flash_color %>'>
  <div class='cotainer'>
    <%= render flash_path, object: flash_object %>
  </div>
</div>

app/views/application/_navigation.html.erb
<div class="bs-example bs-navbar-top-example">
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <!-- We use the fluid option here to avoid overriding the fixed width of a normal container within the narrow content columns. -->
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-6">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Blog</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-6">
          <ul class="nav navbar-nav">
            <li><%= link_to "Posts", posts_path %></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>
  </div>

app/views/application/phone/_left_panel.html.erb
<!-- Left panel with reveal effect-->
<div class="panel panel-left panel-reveal">
  <div class='list-block'>
    <ul>
      <%= panel_link text: "New Post", icon: 'edit', path: new_post_path %>
      <%= panel_link text: "All Posts", icon: 'bars', path: posts_path %>
    </ul>
  </div>
</div>

app/views/application/phone/_panel_link.html.erb
<li>
  <%= link_to path, class: 'close-panel item-link' do %>
    <div class='item-content'>
      <div class='item-media'>
        <%= icon icon_name %>
      </div>
      <div class='item-inner'>
        <div class='item-title'><%= text %></div>
      </div>
    </div>
  <% end %>
</li>

app/views/comments/_approved.html.erb
<%= div_for comment do %>
  <div class='content'>
    <%= comment.body %>
  </div>
<% end %>

app/views/comments/_comment.html.erb
<%= render "comments/#{comment.state}", comment: comment %>

app/views/comments/_require_approval.html.erb
<%= div_for comment do %>
  <div class='content'>
    <%= comment.body %>
  </div>
<% end %>

app/views/comments/create.js.erb
["#comments", "<%= xms_event %>", "<%= j render @comment %>"]

app/views/layouts/application.html+phone.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags-->
    <%= favicon_link_tag 'favicon.ico' %>
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', rel: 'apple-touch-icon', type: 'image/png' %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no, minimal-ui">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <!-- Your app title -->
    <title>Blog Me Now</title>
    <!-- Path to Framework7 Library CSS-->
    <%= stylesheet_link_tag    "phone", media: "all", "data-turbolinks-track" => true %>
  </head>
  <body class='phone'>
    <!-- Status bar overlay for full screen mode (PhoneGap) -->
    <div class="statusbar-overlay"></div>
    <!-- Panels overlay-->
    <div class="panel-overlay"></div>
    <%= render 'application/phone/left_panel' %>
    <!-- Views -->
    <div class="views">
      <div class="view view-main">
        <%= yield %>
      </div>
    </div>
    <%= javascript_include_tag "phone" %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogmenow</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'navigation' %>
<%= render_flash %>
<div class='container'>
  <%= yield %>
</div>

</body>
</html>

app/views/pages/home.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <div class='left'>
      <a href='#' class='link icon-only open-panel'>
        <i class='icon icon-bars-blue'></i>
      </a>
    </div>
    <div class='center'>
      Blog Me Now
    </div>
  </div>
</div>


<div class="pages navbar-through toolbar-through">
  <div class='page'>
    <div class='page-content'>

    </div>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_for @post, html:  { role: 'form', class: 'col-md-6 col-md-offset-3' } do |f| %>
  <div class='form-group'>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control' %>
  </div>
  <%= f.submit "Save", class: 'btn btn-primary' %>
<% end %>

app/views/posts/_post.html+phone.erb
<li>
  <%= link_to post, class: 'item-link item-content' do %>
    <div class='item-inner'>
      <div class='item-title-row'><%= post.title %></div>
      <div class='item-subtitle'><%= post.body %></div>
    </div>
  <% end %>
</li>

app/views/posts/_post.html.erb
<%= div_for post, class: 'row' do %>
  <div class='col-md-10'>
    <h2><%= link_to post.title, post %></h2>
    <div>
      <% post.tags.each do |tag| %>
        <%= "#{tag.name} (#{@tags_posts_count[tag.id]})" %>
      <% end %>
    </div>

  </div>
  <div class='col-md-2'>
    <%= link_to "Edit", edit_post_path(post), class: 'btn btn-default' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit: <%= @post.title %></h1>
<%= render 'form' %>

app/views/posts/flash/create/_error.html.erb
<h4>Sorry but your form wasn't valid</h4>
<%= render 'error_list', target: @post %>
<%= link_to "Back to Index", posts_path %>

app/views/posts/flash/create/_success.html.erb
<h4>Congratulations</h4>
Your post has been successfully created! <%= link_to "edit: #{object.title}", edit_post_path(object) %>

app/views/posts/flash/update/_error.html.erb
Sorry but we couldn't update your post.

app/views/posts/flash/update/_success.html.erb
Your post has been successfully saved! <%= link_to object.title, object %>

app/views/posts/index.html+phone.erb
<div class="navbar">
  <div class="navbar-inner">
    <div class='left'>
      <a href='#' class='link icon-only open-panel'>
        <i class='icon icon-bars-blue'></i>
      </a>
    </div>
    <div class='center'>
      All posts
    </div>
  </div>
</div>


<div class='page'>
  <div class='page-content'>
    <div class='list-block media-list'>
      <ul>
        <%= render @posts %>
      </ul>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<%= link_to "New Post", new_post_path %>

<div id='categories'>
  <% @categories.each do |category| %>
    <h2><%= "#{category.name} (#{category.posts_count})" %><h2>
  <% end %>
</div>

<div id='posts'>
  <%= render @posts %>
</div>

app/views/posts/new.html+phone.erb
<div class="navbar">
  <div class="navbar-inner">
    <div class="left sliding">
      <%= link_to posts_path, class: 'back link' do %>
        <i class='icon icon-back-blue'></i>
        <span>Back</span>
      <% end %>
    </div>
    <div class='center'>
      <%= @post.title %>
    </div>
  </div>
</div>

<div class='page'>
  <div class='page-content'>
    <div class='content-block-title'>
      New Post
    </div>
    <%= form_for @post do |f| %>
    <div class='list-block'>
      <ul>
        <li>
          <div class='item-content'>
            <div class='item-inner'>
              <div class='item-title label'>Title</div>
              <div class='item-input'>
                <%= f.text_field :title %>
              </div>
            </div>
          </div>
        </li>
        <li class='align-top'>
          <div class='item-content'>
            <div class='item-inner'>
              <div class='item-title label'>Body</div>
              <div class='item-input'>
                <%= f.text_area :body %>
              </div>
            </div>
          </div>
        </li>
      </ul>
    </div>
    <div class='content-block'>
      <div class='row'>
        <div class='col-100'>
          <%= f.submit "Save", class: 'button button-big button-submit' %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render 'form' %>

app/views/posts/show.html+phone.erb
<div class="navbar">
  <div class="navbar-inner">
    <div class="left sliding">
      <%= link_to posts_path, class: 'back link' do %>
        <i class='icon icon-back-blue'></i>
        <span>Back</span>
      <% end %>
    </div>
    <div class='center'>
      <%= @post.title %>
    </div>
  </div>
</div>

<div class='page'>
  <div class='page-content'>
    <div class='content-block-title'><%= @post.title %></div>
    <div class='content-block'>
      <div class='content-block-inner'>
        <%= simple_format @post.body %>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>


<%= simple_format @post.body %>

<div id='comments'>
  <%= render @post.comments %>
</div>

<h5>Add a Comment</h5>
<%= form_for [@post, @post.comments.build], remote: true do |f| %>
  <div class='form-group'>
    <%= f.text_area :body, class: 'form-control' %>
  </div>
  <%= f.submit "Create", class: 'btn btn-default' %>
<% end %>